/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.adminrole;

import java.awt.CardLayout;
import javax.swing.JPanel;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Shah's
 */
public class AddPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPersonJPanel
     */
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    public AddPersonJPanel(JPanel userProcessContainer, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcomboCity = new javax.swing.JComboBox<>();
        lblAge = new javax.swing.JLabel();
        jcomboCommunity = new javax.swing.JComboBox<>();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        lblHouse = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        lblZipcode = new javax.swing.JLabel();
        btnAddPersonSubmit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBackAddPerson = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();

        jcomboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston" }));

        lblAge.setText("Age:");

        jcomboCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huntington Avenue", "Long wood", "City View" }));

        lblCity.setText("City:");

        lblCommunity.setText("Community:");

        lblHouse.setText("House:");

        lblZipcode.setText("Zipcode:");

        btnAddPersonSubmit.setText("Submit");
        btnAddPersonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonSubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Person");

        btnBackAddPerson.setText("<< Back");
        btnBackAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAddPersonActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnBackAddPerson))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName)
                            .addComponent(lblAge)
                            .addComponent(lblCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHouse)
                            .addComponent(lblZipcode)
                            .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(jcomboCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcomboCommunity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHouse)
                            .addComponent(txtZipcode)
                            .addComponent(txtAge)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btnAddPersonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackAddPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity)
                    .addComponent(jcomboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCommunity)
                    .addComponent(jcomboCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHouse)
                    .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZipcode)
                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnAddPersonSubmit)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonSubmitActionPerformed
        // TODO add your handling code here:
        String personName = txtName.getText();
//        Integer age = Integer.parseInt(txtAge.getText());
        String city = jcomboCity.getSelectedItem().toString();
        String community = jcomboCommunity.getSelectedItem().toString();
//        Integer house = Integer.parseInt(txtHouse.getText());
//        Integer zipcode = Integer.parseInt(txtZipcode.getText());
        
        //regex pattern for a valid Person name
        String carname_pattern = "^[a-zA-Z]{0,30}+";
        Pattern exp = Pattern.compile(carname_pattern);
        
        //regex pattern for a valid serial number
        String serialnum_pattern = "^[1-9]{2}+";
        Pattern exp1 = Pattern.compile(serialnum_pattern);
        
        //regex pattern for a valid zipcode number
        String zipcode_pattern = "^[0-9]{5}+";
        Pattern exp2 = Pattern.compile(zipcode_pattern);
        
        if(personName.isEmpty() || txtAge.getText().isEmpty() || city.isEmpty() || 
            community.isEmpty() ||  txtHouse.getText().isEmpty() || txtZipcode.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this,"All Fields are required!");
        }else{
            Matcher match = exp.matcher(personName);
            if(!match.matches()){
               JOptionPane.showMessageDialog(this,"Name is Incorrect!!");
            }else{
               Matcher match1 = exp1.matcher(txtAge.getText()); 
               if(!match1.matches()){
                    JOptionPane.showMessageDialog(this,"Age is Incorrect!!");
               }else{
                   Matcher match2 = exp1.matcher(txtHouse.getText());
                   if(!match2.matches()){
                        JOptionPane.showMessageDialog(this,"House Number is Incorrect!!");
                   }else{
                      Matcher match3 = exp2.matcher(txtZipcode.getText()); 
                      if(!match3.matches()){
                        JOptionPane.showMessageDialog(this,"Zipcode Number is Incorrect!!");
                      }else{
                        Person person = personDirectory.newPerson();
                        person.setPersonName(personName);
                        //person.setAge(age);
                        person.setCity(city);
                        person.setCommunity(community);
                        //person.setHouse(house);
                        //person.setZipcode(zipcode);
                        //person.setPatientID(count);
                        try{
                            person.setAge(Integer.parseInt(txtAge.getText()));
                            person.setHouse(Integer.parseInt(txtHouse.getText()));
                            person.setZipcode(Integer.parseInt(txtZipcode.getText()));
                        }catch(NumberFormatException e){// handle your exception
                            e.printStackTrace();
                        }
                        JOptionPane.showMessageDialog(this,"New Person Added!!");
        
                        clearField();
                      }
                   } 
               }
            }
        }
    }//GEN-LAST:event_btnAddPersonSubmitActionPerformed

    private void btnBackAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAddPersonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackAddPersonActionPerformed

    private void clearField()
    {
        txtName.setText("");
        txtAge.setText("");
        txtHouse.setText("");
        txtZipcode.setText("");
        jcomboCity.setSelectedItem("Boston");
        jcomboCommunity.setSelectedItem("Huntington Avenue");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPersonSubmit;
    private javax.swing.JButton btnBackAddPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcomboCity;
    private javax.swing.JComboBox<String> jcomboCommunity;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables
}
