/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Product;

/**
 *
 * @author Shah's
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    String selectedBioImagePath;
    String selectedPhotoImagePath;
    
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGeoData = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblTeleNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtGeoData = new javax.swing.JTextField();
        txtTeleNum = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblMedNum = new javax.swing.JLabel();
        lblHealthNum = new javax.swing.JLabel();
        lblBankNum = new javax.swing.JLabel();
        lblLicenceNum = new javax.swing.JLabel();
        lblVhclNum = new javax.swing.JLabel();
        lblDeviceNum = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        lblBioId = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblUniqueID = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtMedNum = new javax.swing.JTextField();
        txtHealthNum = new javax.swing.JTextField();
        txtBankNum = new javax.swing.JTextField();
        txtLicenceNum = new javax.swing.JTextField();
        txtDeviceNum = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtVhclNum = new javax.swing.JTextField();
        txtUniqueId = new javax.swing.JTextField();
        lblErrgeo = new javax.swing.JLabel();
        txtDOB = new com.toedter.calendar.JDateChooser();
        lblErrGeoData = new javax.swing.JLabel();
        btnPhoto = new javax.swing.JButton();
        btnBioPhoto = new javax.swing.JButton();
        lblErrName = new javax.swing.JLabel();
        lblErrTele = new javax.swing.JLabel();
        lblErrFax = new javax.swing.JLabel();
        lblErrEmail = new javax.swing.JLabel();
        lblErrSSN = new javax.swing.JLabel();
        lblErrMedRec = new javax.swing.JLabel();
        lblErrHealth = new javax.swing.JLabel();
        lblErrVhcl = new javax.swing.JLabel();
        lblErrBank = new javax.swing.JLabel();
        lblErrLic = new javax.swing.JLabel();
        lblErrDevice = new javax.swing.JLabel();
        lblErrIp = new javax.swing.JLabel();
        lblErrLinkedin = new javax.swing.JLabel();
        lblErrBio = new javax.swing.JLabel();
        lblErrUnique = new javax.swing.JLabel();
        lblErrPhoto = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create form");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        lblGeoData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGeoData.setText("Geographical Data:");

        lblDOB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDOB.setText("Date Of Birth:");

        lblTeleNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTeleNum.setText("Telephone Number:");

        lblFaxNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFaxNum.setText("Fax Number:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblSSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSSN.setText("Social Security Number:");

        txtGeoData.setRequestFocusEnabled(false);
        txtGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoDataActionPerformed(evt);
            }
        });

        txtTeleNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleNumActionPerformed(evt);
            }
        });
        txtTeleNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTeleNumKeyReleased(evt);
            }
        });

        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });
        txtFaxNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNumKeyReleased(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        lblMedNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMedNum.setText("Medical Record Number:");

        lblHealthNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHealthNum.setText("Healthplan beneficiary Number:");

        lblBankNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBankNum.setText("Bank Account Number:");

        lblLicenceNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLicenceNum.setText("Certificate/licence Number:");

        lblVhclNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVhclNum.setText("Vehicle Number:");

        lblDeviceNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeviceNum.setText("Device Number:");

        lblLinkedIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinkedIn.setText("LinkedIn:");

        lblIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIP.setText("IP Address:");

        lblBioId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBioId.setText("Biometric Identifiers:");

        lblPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhoto.setText("Photo:");

        lblUniqueID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUniqueID.setText("Unique ID Number:");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSSNKeyReleased(evt);
            }
        });

        txtMedNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedNumActionPerformed(evt);
            }
        });

        txtHealthNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthNumActionPerformed(evt);
            }
        });

        txtBankNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNumActionPerformed(evt);
            }
        });
        txtBankNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankNumKeyReleased(evt);
            }
        });

        txtLicenceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenceNumActionPerformed(evt);
            }
        });

        txtDeviceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceNumActionPerformed(evt);
            }
        });
        txtDeviceNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDeviceNumKeyReleased(evt);
            }
        });

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });
        txtLinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedInKeyReleased(evt);
            }
        });

        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });
        txtIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIPKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtVhclNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVhclNumActionPerformed(evt);
            }
        });
        txtVhclNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVhclNumKeyReleased(evt);
            }
        });

        txtUniqueId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIdActionPerformed(evt);
            }
        });

        lblErrgeo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrgeo.setForeground(new java.awt.Color(255, 51, 51));

        lblErrGeoData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrGeoData.setForeground(new java.awt.Color(204, 51, 0));

        btnPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPhoto.setText("Upload");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        btnBioPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBioPhoto.setText("Upload");
        btnBioPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBioPhotoActionPerformed(evt);
            }
        });

        lblErrName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrName.setForeground(new java.awt.Color(255, 51, 51));

        lblErrTele.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrTele.setForeground(new java.awt.Color(255, 51, 51));

        lblErrFax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrFax.setForeground(new java.awt.Color(255, 51, 51));

        lblErrEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrEmail.setForeground(new java.awt.Color(255, 51, 51));

        lblErrSSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrSSN.setForeground(new java.awt.Color(255, 51, 51));

        lblErrMedRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrMedRec.setForeground(new java.awt.Color(255, 51, 51));

        lblErrHealth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrHealth.setForeground(new java.awt.Color(255, 51, 51));

        lblErrVhcl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrVhcl.setForeground(new java.awt.Color(255, 51, 51));

        lblErrBank.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrBank.setForeground(new java.awt.Color(255, 51, 51));

        lblErrLic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrLic.setForeground(new java.awt.Color(255, 51, 51));

        lblErrDevice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrDevice.setForeground(new java.awt.Color(255, 51, 51));

        lblErrIp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrIp.setForeground(new java.awt.Color(255, 51, 51));

        lblErrLinkedin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrLinkedin.setForeground(new java.awt.Color(255, 51, 51));

        lblErrBio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrBio.setForeground(new java.awt.Color(255, 51, 51));

        lblErrUnique.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrUnique.setForeground(new java.awt.Color(255, 51, 51));

        lblErrPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErrPhoto.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDOB)
                                                .addComponent(lblTeleNum)
                                                .addComponent(lblFaxNum)
                                                .addComponent(lblGeoData)
                                                .addComponent(lblName)
                                                .addComponent(lblEmail)
                                                .addComponent(lblSSN)
                                                .addComponent(lblMedNum)))
                                        .addComponent(lblLicenceNum)
                                        .addComponent(lblVhclNum)
                                        .addComponent(lblDeviceNum)
                                        .addComponent(lblLinkedIn)
                                        .addComponent(lblIP)
                                        .addComponent(lblBioId)
                                        .addComponent(lblPhoto)
                                        .addComponent(lblUniqueID))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFaxNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTeleNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtGeoData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLicenceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtVhclNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnBioPhoto)
                                                .addComponent(btnPhoto))))))
                            .addComponent(lblHealthNum)
                            .addComponent(lblBankNum))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErrgeo)
                                .addGap(16, 16, 16)
                                .addComponent(lblErrGeoData))
                            .addComponent(lblErrName)
                            .addComponent(lblErrTele)
                            .addComponent(lblErrFax)
                            .addComponent(lblErrEmail)
                            .addComponent(lblErrSSN)
                            .addComponent(lblErrMedRec)
                            .addComponent(lblErrHealth)
                            .addComponent(lblErrVhcl)
                            .addComponent(lblErrBank)
                            .addComponent(lblErrLic)
                            .addComponent(lblErrDevice)
                            .addComponent(lblErrIp)
                            .addComponent(lblErrLinkedin)
                            .addComponent(lblErrBio)
                            .addComponent(lblErrUnique)
                            .addComponent(lblErrPhoto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrGeoData)
                    .addComponent(lblErrgeo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeleNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrTele)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFaxNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrFax)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrEmail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSSN)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrSSN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrMedRec))
                    .addComponent(lblMedNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHealthNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrHealth)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBankNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrBank)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenceNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLicenceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrLic)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVhclNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVhclNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrVhcl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeviceNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrDevice)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLinkedIn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrLinkedin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIP)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrIp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBioId)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBioPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrBio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPhoto)
                                .addComponent(lblErrPhoto)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUniqueID)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrUnique)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1550, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtDeviceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceNumActionPerformed

    private void txtLicenceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenceNumActionPerformed

    private void txtBankNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNumActionPerformed

    private void txtMedNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedNumActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtHealthNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthNumActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtTeleNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleNumActionPerformed

    private void txtGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoDataActionPerformed

    private void txtVhclNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVhclNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVhclNumActionPerformed

    private void txtUniqueIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(txtName.getText().isEmpty()||txtGeoData.getText().isEmpty()||
                txtEmail.getText().isEmpty()||txtLicenceNum.getText().isEmpty()||
                txtVhclNum.getText().isEmpty()||txtDeviceNum.getText().isEmpty()||
                txtLinkedIn.getText().isEmpty()||txtIP.getText().isEmpty()||
                txtUniqueId.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"All Fields are required!");
        }else{ 
            
            //JOptionPane.showMessageDialog(this,txtName.getText());
            
            //Get Date
            SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault());
            //Define the format of Date
            String mydate = sf.format(txtDOB.getDate());
            
            product.setName(txtName.getText());
            product.setGeoData(txtGeoData.getText());
            product.setDateOfBirth(mydate);
            product.setTelephoneNum(Long.parseLong(txtTeleNum.getText()));
            product.setFaxNum(Long.parseLong(txtFaxNum.getText()));
            product.setEmail(txtEmail.getText());
            product.setSsn(Long.parseLong(txtSSN.getText()));
            product.setMedRecNum(Long.parseLong(txtMedNum.getText()));
            product.setHealthPlanNum(Long.parseLong(txtHealthNum.getText()));
            product.setBankAccNum(Long.parseLong(txtBankNum.getText()));
            product.setLicenceNum(txtLicenceNum.getText());
            product.setVehicleLicPlate(txtVhclNum.getText());
            product.setDeviceIdenNum(txtDeviceNum.getText()); 
            product.setLinkedIn(txtLinkedIn.getText());
            product.setIpAdd(txtIP.getText());
            //product.setBiometricIdentifier(txtBioId.getText());
            //product.setPhoto(txtPhoto.getText());
            product.setUniqueID(txtUniqueId.getText());
            JOptionPane.showMessageDialog(this,"Information Saved!!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z\\s]{0,30}+"; 
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtName.getText());
        if(!match.matches()){
            lblErrName.setText("Name is Incorrect!!");
        }else{    
            lblErrName.setText(null);
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
       JFileChooser browseImageFile = new JFileChooser();
       
       FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png","jpg","jpeg");
       browseImageFile.addChoosableFileFilter(fnef);
       
       int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedPhotoImagePath = selectedImageFile.getAbsolutePath();
            product.setPhotoImagePath(selectedPhotoImagePath);
        }
    }//GEN-LAST:event_btnPhotoActionPerformed

    private void btnBioPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBioPhotoActionPerformed
        // TODO add your handling code here:
       JFileChooser browseImageFile = new JFileChooser();
       
       FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png","jpg","jpeg");
       browseImageFile.addChoosableFileFilter(fnef);
       
       int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedBioImagePath = selectedImageFile.getAbsolutePath();
            product.setBioImagePath(selectedBioImagePath);
            //JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlabel
        }
    }//GEN-LAST:event_btnBioPhotoActionPerformed

    private void txtFaxNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^((?!(0))[0-9]{10})$"; 
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtFaxNum.getText());
        if(!match.matches()){
            lblErrFax.setText("Fax Number is Incorrect!!");
        }else{    
            lblErrFax.setText(null);
        }
    }//GEN-LAST:event_txtFaxNumKeyReleased

    private void txtTeleNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleNumKeyReleased
        // TODO add your handling code here:
        //String PATTERN = "^(\\+0?1\\s)?\\(?\\[1-9]{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$"; 
        String PATTERN = "^((?!(0))[0-9]{10})$";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtTeleNum.getText());
        if(!match.matches()){
            lblErrTele.setText("Telephone Number is Incorrect!!");
        }else{ 
            if(txtTeleNum.getText().length()<10){
                txtTeleNum.setText(null);
                lblErrTele.setText("Please Enter a valid Mobile Number!!");
            }else{
                lblErrTele.setText(null);
            }
        }
    }//GEN-LAST:event_txtTeleNumKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^([a-zA-Z]{1,15})@([a-zA-Z]{1,10}).[a-zA-Z]{1,10}$";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtEmail.getText());
        if(!match.matches()){
            lblErrEmail.setText("Email Address is Incorrect!!");
        }else{    
            lblErrEmail.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtSSNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{10}$";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtSSN.getText());
        if(!match.matches()){
            lblErrSSN.setText("SSN is Incorrect!!");
        }else{    
            lblErrSSN.setText(null);
        }
    }//GEN-LAST:event_txtSSNKeyReleased

    private void txtBankNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankNumKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,11}+";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtBankNum.getText());
        if(!match.matches()){
            lblErrBank.setText("Bank Number is Incorrect!!");
        }else{    
            lblErrBank.setText(null);
        }
    }//GEN-LAST:event_txtBankNumKeyReleased

    private void txtDeviceNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeviceNumKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,14}+";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtDeviceNum.getText());
        if(!match.matches()){
            lblErrDevice.setText("Device Number is Incorrect!!");
        }else{    
            lblErrDevice.setText(null);
        }
    }//GEN-LAST:event_txtDeviceNumKeyReleased

    private void txtVhclNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVhclNumKeyReleased
        // TODO add your handling code here:
       String PATTERN = "^[a-zA-Z0-9]+";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtVhclNum.getText());
        if(!match.matches()){
            lblErrVhcl.setText("Vehicle Number is Incorrect!!");
        }else{    
            lblErrVhcl.setText(null);
        } 
    }//GEN-LAST:event_txtVhclNumKeyReleased

    private void txtIPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPKeyReleased
        // TODO add your handling code here:
        String PATTERN = "(\\\\d{1,2}|(0|1)\\\\d{2}|2[0-4]\\\\d|25[0-5])";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtIP.getText());
        if(!match.matches()){
            lblErrIp.setText("IP Address is Incorrect!!");
        }else{    
            lblErrIp.setText(null);
        } 
    }//GEN-LAST:event_txtIPKeyReleased

    private void txtLinkedInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedInKeyReleased
        // TODO add your handling code here:
        //^https:\/\/[a-z]{2,3}\.linkedin\.com\/.*$
        String PATTERN = "^https:\\/\\/[a-z]{2,3}\\.linkedin\\.com\\/.*$";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtLinkedIn.getText());
        if(!match.matches()){
            lblErrLinkedin.setText("Not a correct url!!");
        }else{    
            lblErrLinkedin.setText(null);
        } 
    }//GEN-LAST:event_txtLinkedInKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBioPhoto;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblBankNum;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceNum;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrBank;
    private javax.swing.JLabel lblErrBio;
    private javax.swing.JLabel lblErrDevice;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrFax;
    private javax.swing.JLabel lblErrGeoData;
    private javax.swing.JLabel lblErrHealth;
    private javax.swing.JLabel lblErrIp;
    private javax.swing.JLabel lblErrLic;
    private javax.swing.JLabel lblErrLinkedin;
    private javax.swing.JLabel lblErrMedRec;
    private javax.swing.JLabel lblErrName;
    private javax.swing.JLabel lblErrPhoto;
    private javax.swing.JLabel lblErrSSN;
    private javax.swing.JLabel lblErrTele;
    private javax.swing.JLabel lblErrUnique;
    private javax.swing.JLabel lblErrVhcl;
    private javax.swing.JLabel lblErrgeo;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthNum;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblLicenceNum;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTeleNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblVhclNum;
    private javax.swing.JTextField txtBankNum;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtDeviceNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthNum;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLicenceNum;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTeleNum;
    private javax.swing.JTextField txtUniqueId;
    private javax.swing.JTextField txtVhclNum;
    // End of variables declaration//GEN-END:variables
}
