/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author Shah's
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    Product product;
    String selectedImagePath;
    
    public ViewJPanel(Product product) {
        initComponents();
        this.product = product;
        displayProduct();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelephoneNum = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMedNum = new javax.swing.JTextField();
        txtHealthNum = new javax.swing.JTextField();
        lblFaxNum = new javax.swing.JLabel();
        txtBankNum = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtLicenceNum = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtGeoData = new javax.swing.JTextField();
        txtDeviceNum = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtTeleNum = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblMedNum = new javax.swing.JLabel();
        lblHealthNum = new javax.swing.JLabel();
        lblBankNum = new javax.swing.JLabel();
        lblLicenceNum = new javax.swing.JLabel();
        lblVhclNum = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblDeviceNum = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        txtVhclNum = new javax.swing.JTextField();
        lblBioId = new javax.swing.JLabel();
        txtUniqueId = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        lblUniqueID = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblTeleNum = new javax.swing.JLabel();
        JlblPhotoDspl = new javax.swing.JLabel();
        txtPhoto = new javax.swing.JLabel();
        JlblBioDspl = new javax.swing.JLabel();

        txtTelephoneNum.setEditable(false);
        txtTelephoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Name:");

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtMedNum.setEditable(false);
        txtMedNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedNumActionPerformed(evt);
            }
        });

        txtHealthNum.setEditable(false);
        txtHealthNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthNumActionPerformed(evt);
            }
        });

        lblFaxNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFaxNum.setText("Fax Number:");

        txtBankNum.setEditable(false);
        txtBankNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNumActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        txtLicenceNum.setEditable(false);
        txtLicenceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenceNumActionPerformed(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSSN.setText("Social Security Number:");

        txtGeoData.setEditable(false);
        txtGeoData.setRequestFocusEnabled(false);
        txtGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoDataActionPerformed(evt);
            }
        });

        txtDeviceNum.setEditable(false);
        txtDeviceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceNumActionPerformed(evt);
            }
        });

        txtDOB.setEditable(false);
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        txtLinkedIn.setEditable(false);
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        txtTeleNum.setEditable(false);
        txtTeleNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleNumActionPerformed(evt);
            }
        });

        txtIP.setEditable(false);
        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });

        txtFaxNum.setEditable(false);
        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblMedNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMedNum.setText("Medical Record Number:");

        lblHealthNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHealthNum.setText("Healthplan beneficiary Number:");

        lblBankNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBankNum.setText("Bank Account Number:");

        lblLicenceNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLicenceNum.setText("Certificate/licence Number:");

        lblVhclNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVhclNum.setText("Vehicle Number:");

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("View");

        lblDeviceNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeviceNum.setText("Device Number:");

        lblLinkedIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinkedIn.setText("LinkedIn:");

        lblIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIP.setText("IP Address:");

        txtVhclNum.setEditable(false);
        txtVhclNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVhclNumActionPerformed(evt);
            }
        });

        lblBioId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBioId.setText("Biometric Identifiers:");

        txtUniqueId.setEditable(false);
        txtUniqueId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIdActionPerformed(evt);
            }
        });

        lblPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhoto.setText("Photo:");

        lblUniqueID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUniqueID.setText("Unique ID Number:");

        lblGeoData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGeoData.setText("Geographical Data:");

        txtSSN.setEditable(false);
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDOB.setText("Date Of Birth:");

        lblTeleNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTeleNum.setText("Telephone Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(779, 779, 779))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1078, 1078, 1078)
                        .addComponent(txtTelephoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblGeoData)
                                    .addComponent(lblDOB)
                                    .addComponent(lblTeleNum)
                                    .addComponent(lblFaxNum)
                                    .addComponent(lblEmail)
                                    .addComponent(lblSSN)
                                    .addComponent(lblMedNum)
                                    .addComponent(lblHealthNum)))
                            .addComponent(lblBankNum)
                            .addComponent(lblLicenceNum)
                            .addComponent(lblVhclNum)
                            .addComponent(lblDeviceNum)
                            .addComponent(lblLinkedIn)
                            .addComponent(lblIP)
                            .addComponent(lblUniqueID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBioId)
                                            .addComponent(lblPhoto)))
                                    .addComponent(txtMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLicenceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JlblPhotoDspl, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPhoto))
                                    .addComponent(JlblBioDspl, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtVhclNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBioId)
                    .addComponent(JlblBioDspl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGeoData)
                                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTeleNum)
                            .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFaxNum)
                            .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(lblPhoto)
                        .addGap(72, 72, 72)
                        .addComponent(txtPhoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMedNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHealthNum)
                                    .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JlblPhotoDspl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankNum)
                            .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLicenceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicenceNum))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVhclNum)
                    .addComponent(txtVhclNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceNum)
                    .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIP)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUniqueID)
                    .addComponent(txtUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 626, Short.MAX_VALUE)
                .addComponent(txtTelephoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelephoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtMedNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedNumActionPerformed

    private void txtHealthNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthNumActionPerformed

    private void txtBankNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNumActionPerformed

    private void txtLicenceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenceNumActionPerformed

    private void txtGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoDataActionPerformed

    private void txtDeviceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceNumActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtTeleNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleNumActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtVhclNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVhclNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVhclNumActionPerformed

    private void txtUniqueIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIdActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblBioDspl;
    private javax.swing.JLabel JlblPhotoDspl;
    private javax.swing.JLabel lblBankNum;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceNum;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthNum;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblLicenceNum;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTeleNum;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblVhclNum;
    private javax.swing.JTextField txtBankNum;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeviceNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthNum;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLicenceNum;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel txtPhoto;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTeleNum;
    private javax.swing.JTextField txtTelephoneNum;
    private javax.swing.JTextField txtUniqueId;
    private javax.swing.JTextField txtVhclNum;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
       txtName.setText(product.getName());
       txtGeoData.setText(product.getGeoData());
       txtDOB.setText(product.getDateOfBirth());
       txtTeleNum.setText(Long.toString(product.getTelephoneNum()));
       txtFaxNum.setText(Long.toString(product.getFaxNum()));
       txtEmail.setText(product.getEmail());
       txtSSN.setText(Long.toString(product.getSsn()));
       txtMedNum.setText(Long.toString(product.getMedRecNum()));
       txtHealthNum.setText(Long.toString(product.getHealthPlanNum()));
       txtBankNum.setText(Long.toString(product.getBankAccNum()));
       txtLicenceNum.setText(product.getLicenceNum());
       txtVhclNum.setText(product.getVehicleLicPlate());
       txtDeviceNum.setText(product.getDeviceIdenNum());
       txtLinkedIn.setText(product.getLinkedIn());
       txtIP.setText(product.getIpAdd());
       txtUniqueId.setText(product.getUniqueID());
       
       //JOptionPane.showMessageDialog(null, selectedImagePath);
       ImageIcon photo = new ImageIcon(product.getphotoImagePath());
       Image image = photo.getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT);
       JlblPhotoDspl.setIcon(new ImageIcon(image));
       
       ImageIcon bio = new ImageIcon(product.getbioImagePath());
       Image image1 = bio.getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT);
       JlblBioDspl.setIcon(new ImageIcon(image1));
       
    }
}
