/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.carAllDataList;
import model.carfleet;

/**
 *
 * @author Shah's
 */
public class AddCarDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCarDataJPanel
     */
    carAllDataList alldata;
    public AddCarDataJPanel(carAllDataList alldata) {
        initComponents();
        this.alldata = alldata; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddTitle = new javax.swing.JLabel();
        lblSerialNum = new javax.swing.JLabel();
        lblCarName = new javax.swing.JLabel();
        lblManuName = new javax.swing.JLabel();
        lblSeatNum = new javax.swing.JLabel();
        lblManuYear = new javax.swing.JLabel();
        lblModelNum = new javax.swing.JLabel();
        lblMaintainance = new javax.swing.JLabel();
        lblUber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        txtYear = new com.toedter.calendar.JYearChooser();
        txtSerialNum = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        jComboCity = new javax.swing.JComboBox<>();
        cbUber = new javax.swing.JCheckBox();
        jComboSeat = new javax.swing.JComboBox<>();
        jComboCompany = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        cbMaintainance = new javax.swing.JCheckBox();
        lblErrCarName = new javax.swing.JLabel();
        lblErrSerialNum = new javax.swing.JLabel();
        lblErrModelNum = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        lblAddTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAddTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAddTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddTitle.setText("Add Car Details");

        lblSerialNum.setText("Serial Number:");

        lblCarName.setText("Car Name:");

        lblManuName.setText("Manufacturer Name:");

        lblSeatNum.setText("Total Car Seat:");

        lblManuYear.setText("Manufacturing Year:");

        lblModelNum.setText("Model Number:");

        lblMaintainance.setText("Maintainance Expiary Date:");

        lblUber.setText("Uber Availability:");

        lblCity.setText("City Availability:");

        txtCarName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarNameKeyPressed(evt);
            }
        });

        txtYear.setMaximum(2021);
        txtYear.setMinimum(1980);

        txtSerialNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerialNumKeyPressed(evt);
            }
        });

        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModelKeyPressed(evt);
            }
        });

        jComboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select--", "Boston", "Texas", "Arlington", "Somerville", "Noorwood", "New York", "Philadelphia", "New Jersy", "Bensalem" }));

        cbUber.setText("Yes");

        jComboSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select--", "3", "4", "5", "6", "7", "8" }));

        jComboCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please Select--", "Toyota", "BMW", "Audi", "Honda" }));
        jComboCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCompanyActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cbMaintainance.setText("Yes");

        lblErrCarName.setForeground(new java.awt.Color(204, 0, 0));

        lblErrSerialNum.setForeground(new java.awt.Color(204, 0, 0));

        lblErrModelNum.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblAddTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManuName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSeatNum, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUber, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaintainance, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUber)
                                    .addComponent(jComboSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMaintainance)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCarName)
                                            .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                            .addComponent(txtSerialNum))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblErrCarName)
                                            .addComponent(lblErrModelNum)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(296, 296, 296)
                                        .addComponent(lblErrSerialNum))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 211, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAddTitle)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrCarName))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManuName)
                    .addComponent(jComboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManuYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeatNum)
                    .addComponent(jComboSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNum)
                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrSerialNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelNum)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrModelNum)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(lblUber)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cbUber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(jComboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintainance)
                    .addComponent(cbMaintainance))
                .addGap(47, 47, 47)
                .addComponent(btnSave)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            try{
                ArrayList<Integer> unqname = new ArrayList<>();
                for(carfleet ncar: alldata.getAlldata()){
                if(!(unqname.contains(ncar.getSerialNum()))){
                unqname.add(ncar.getSerialNum());
                }
                }

                if(unqname.contains(Integer.parseInt(txtSerialNum.getText()))) {

                JOptionPane.showMessageDialog(this, "Enter unique serial number ");
                }
                } catch(Exception e){
                System.out.println("Error in serial no check " +e);
            }
            String carname = txtCarName.getText();
            String manufaturing_company = jComboCompany.getSelectedItem().toString();
            String carseat = jComboSeat.getSelectedItem().toString();
            String serial_num = txtSerialNum.getText();
            String model_num = txtModel.getText();
            Boolean uber_check = cbUber.isSelected();
            String citycombo = jComboCity.getSelectedItem().toString();
            Boolean maintainance_check = cbMaintainance.isSelected();
            int year = txtYear.getYear();  //Get Year
            
            //regex pattern for a valid car name
            String carname_pattern = "^[a-zA-Z]{0,30}+";
            Pattern exp = Pattern.compile(carname_pattern);
            
            //regex pattern for a valid serial number
            String serialnum_pattern = "^[0-9]{6}$+";
            Pattern exp1 = Pattern.compile(serialnum_pattern);
            
            //regex pattern for a valid model number
            String modelnum_pattern = "^[a-zA-Z0-9]+";
            Pattern exp2 = Pattern.compile(modelnum_pattern);
          
            if(carname.isEmpty() || txtSerialNum.getText().isEmpty() || model_num.isEmpty()){
                JOptionPane.showMessageDialog(this,"All Fields are required!");
            }else{ 
                if(manufaturing_company == "--Please Select--" || carseat == "--Please Select--" ||citycombo == "--Please Select--"){
                    JOptionPane.showMessageDialog(this,"Please select valid value! Please Select is not a valid value!!");
                }else{
                    Matcher match = exp.matcher(carname);
                    if(!match.matches()){
                       JOptionPane.showMessageDialog(this,"Name is Incorrect!!");
                    }else{
                        Matcher match1 = exp1.matcher(txtSerialNum.getText());
                        if(!match1.matches()){
                            JOptionPane.showMessageDialog(this,"Serial Number is Incorrect!!");
                        }else{
                            Matcher match2 = exp2.matcher(model_num);
                            if(!match2.matches()){
                                JOptionPane.showMessageDialog(this,"Model Number is Incorrect!!");
                            }else{
                                carfleet anc = alldata.addNewCarData();
                                //carfleet anc1 = alldata.getAlldata();
                                anc.setCarName(carname);
                                anc.setCarManufacturer(manufaturing_company);
                                anc.setManuYear(String.valueOf(year));
                                anc.setTotalSeat(carseat);
                                anc.setUber(String.valueOf(uber_check));
                                //anc.setSerialNum(Integer.parseInt(serial_num));
                                anc.setModelNum(model_num);
                                anc.setCarCity(citycombo);
                                anc.setCarManDate(String.valueOf(maintainance_check));
                                JOptionPane.showMessageDialog(this,"Success!!");
                                //clear the form after submitting data
                                txtCarName.setText("");
                                jComboCompany.setSelectedItem("--Please Select--");
                                jComboSeat.setSelectedItem("--Please Select--");
                                txtSerialNum.setText("");
                                txtModel.setText("");
                                cbUber.setSelected(false);
                                jComboCity.setSelectedItem("--Please Select--");
                                cbMaintainance.setSelected(false);
                                txtYear.setYear(2021);
                                try{
                                   anc.setSerialNum(Integer.parseInt(serial_num));
                                }catch(NumberFormatException e){// handle your exception
                                    e.printStackTrace();
                                }
                            }
                        }
                    }
                }
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCarNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarNameKeyPressed
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,30}+"; 
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtCarName.getText());
        if(!match.matches()){
            lblErrCarName.setText("Name is Incorrect!!");
        }else{    
            lblErrCarName.setText(null);
        }
    }//GEN-LAST:event_txtCarNameKeyPressed

    private void txtSerialNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumKeyPressed
        // TODO add your handling code here:
        String serialNumber = txtSerialNum.getText();
        int length = serialNumber.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        if(length<6){
        txtSerialNum.setEditable(true);
        lblErrSerialNum.setText("Serial Numner should be 6 digits!!");
        }else{
        txtSerialNum.setEditable(false);
        lblErrSerialNum.setText(null);
        }
        }else{
        if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
        txtSerialNum.setEditable(true);

        }else{
        txtSerialNum.setEditable(false);

        }

        }
    }//GEN-LAST:event_txtSerialNumKeyPressed

    private void txtModelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyPressed
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]+"; 
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtModel.getText());
        if(!match.matches()){
            lblErrModelNum.setText("Model Number is Incorrect!!");
        }else{    
            lblErrModelNum.setText(null);
        }
    }//GEN-LAST:event_txtModelKeyPressed

    private void jComboCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCompanyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbMaintainance;
    private javax.swing.JCheckBox cbUber;
    private javax.swing.JComboBox<String> jComboCity;
    private javax.swing.JComboBox<String> jComboCompany;
    private javax.swing.JComboBox<String> jComboSeat;
    private javax.swing.JLabel lblAddTitle;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblErrCarName;
    private javax.swing.JLabel lblErrModelNum;
    private javax.swing.JLabel lblErrSerialNum;
    private javax.swing.JLabel lblMaintainance;
    private javax.swing.JLabel lblManuName;
    private javax.swing.JLabel lblManuYear;
    private javax.swing.JLabel lblModelNum;
    private javax.swing.JLabel lblSeatNum;
    private javax.swing.JLabel lblSerialNum;
    private javax.swing.JLabel lblUber;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerialNum;
    private com.toedter.calendar.JYearChooser txtYear;
    // End of variables declaration//GEN-END:variables
}
